import Foundation
#if canImport(UIKit)
import UIKit
#endif

public struct MockProcessingProvider: ProcessingProviding {
    public enum MockProcessingError: Error, Equatable {
        case requestedFailure
    }

    public var stageDelayNanoseconds: UInt64
    public var shouldFail: Bool

    public init(stageDelayNanoseconds: UInt64 = 450_000_000, shouldFail: Bool = false) {
        self.stageDelayNanoseconds = stageDelayNanoseconds
        self.shouldFail = shouldFail
    }

    public func process(session: CaptureSession, sources: [CaptureSource]) async throws -> ProcessingResult {
        let job = ProcessingJob(sessionID: session.id, stage: .completed, attempts: 1)
        let note = CuratedNote(
            sessionID: session.id,
            title: session.title,
            smartSummary: "Mock processing completed for Phase 0 foundation.",
            detailedSummary: "This placeholder note proves the processing provider boundary without connecting live AI.",
            keyIdeas: ["Capture Session", "Curated Note", "Provider abstraction"],
            confidence: 1.0
        )
        return ProcessingResult(job: job, note: note)
    }

    public func processCreatorPack(
        session: CaptureSession,
        sources: [CaptureSource],
        progress: (PhaseOneProcessingStage) async -> Void
    ) async throws -> CreatorPackProcessingResult {
        if shouldFail {
            throw MockProcessingError.requestedFailure
        }

        for stage in PhaseOneProcessingStage.allCases {
            await progress(stage)
            try await Task.sleep(nanoseconds: stageDelayNanoseconds)
        }

        let job = ProcessingJob(sessionID: session.id, stage: .completed, attempts: 1)
        let note = CuratedNote(
            sessionID: session.id,
            title: session.title,
            smartSummary: "CURA reviewed the imported video locally and prepared a mock Creator Pack.",
            detailedSummary: "This Phase 1 result is generated by a local mock processor. No live AI, Supabase, RevenueCat, authentication, or paid service was used.",
            keyIdeas: ["Imported video preserved locally", "Creator Pack prepared", "Ready for explicit copy or share"],
            quotes: ["Nothing is published without your approval."],
            tags: ["video", "creator-pack", "mock"],
            confidence: 1.0
        )
        let caption = GeneratedOutput(
            sessionID: session.id,
            curatedNoteID: note.id,
            outputType: .creatorPack,
            mode: .create,
            packKey: "creator",
            content: "Captured this moment and turned it into momentum. CURA pulled the key idea from the video and shaped it into a caption I can use next. #CURA #VisionBuilt",
            promptVersion: "mock-phase-1",
            model: "local-mock"
        )
        let pack = OutputPack(
            sessionID: session.id,
            curatedNoteID: note.id,
            packKey: "creator",
            mode: .create,
            outputs: [caption]
        )

        return CreatorPackProcessingResult(job: job, note: note, pack: pack, outputs: [caption])
    }
}

public struct MockTranscriptionProvider: TranscriptionProviding {
    public enum MockTranscriptionError: Error, Equatable {
        case requestedFailure
    }

    public var providerName: String
    public var stageDelayNanoseconds: UInt64
    public var shouldFail: Bool
    public var shouldReturnEmptyTranscript: Bool

    public init(
        providerName: String = "local-demo-mock",
        stageDelayNanoseconds: UInt64 = 1_000_000_000,
        shouldFail: Bool = false,
        shouldReturnEmptyTranscript: Bool = false
    ) {
        self.providerName = providerName
        self.stageDelayNanoseconds = stageDelayNanoseconds
        self.shouldFail = shouldFail
        self.shouldReturnEmptyTranscript = shouldReturnEmptyTranscript
    }

    public func transcribe(
        session: CaptureSession,
        source: CaptureSource,
        progress: @Sendable (TranscriptionProgress) async -> Void
    ) async throws -> TranscriptionResult {
        try Task.checkCancellation()
        await progress(TranscriptionProgress(status: .preparing, fractionCompleted: 0.15))
        try await Task.sleep(nanoseconds: stageDelayNanoseconds)
        try Task.checkCancellation()

        if shouldFail {
            throw MockTranscriptionError.requestedFailure
        }

        await progress(TranscriptionProgress(status: .transcribing, fractionCompleted: 0.55))
        try await Task.sleep(nanoseconds: stageDelayNanoseconds)
        try Task.checkCancellation()

        await progress(TranscriptionProgress(status: .buildingCuratedNote, fractionCompleted: 0.85))
        try await Task.sleep(nanoseconds: stageDelayNanoseconds)
        try Task.checkCancellation()

        if shouldReturnEmptyTranscript {
            return TranscriptionResult(
                transcript: "",
                segments: [],
                suggestedTitle: nil,
                summary: "",
                keyPoints: [],
                actionItems: [],
                providerName: providerName
            )
        }

        let transcript = "Today I recorded a field memo about the launch checklist. Review the audio capture flow, confirm the folder setup, and prepare the next transcription decision before Friday."
        let segments = [
            TranscriptSegment(
                startTime: 0,
                endTime: 6,
                text: "Today I recorded a field memo about the launch checklist.",
                confidence: 0.98
            ),
            TranscriptSegment(
                startTime: 6,
                endTime: 14,
                text: "Review the audio capture flow, confirm the folder setup, and prepare the next transcription decision before Friday.",
                confidence: 0.96
            )
        ]
        let actions = [
            CuratedActionItem(
                title: "Review the audio capture flow",
                supportingExcerpt: "Review the audio capture flow",
                timestamp: 6,
                evidenceState: .explicit
            ),
            CuratedActionItem(
                title: "Confirm the folder setup",
                supportingExcerpt: "confirm the folder setup",
                timestamp: 8,
                evidenceState: .explicit
            ),
            CuratedActionItem(
                title: "Prepare the next transcription decision before Friday",
                supportingExcerpt: "prepare the next transcription decision before Friday",
                timestamp: 10,
                evidenceState: .stronglySupported
            )
        ]

        return TranscriptionResult(
            transcript: transcript,
            segments: segments,
            suggestedTitle: suggestedTitle(from: transcript),
            summary: "A field memo captured the launch checklist and the next decisions needed for the audio transcription path.",
            keyPoints: [
                "The recording is a field memo about the launch checklist.",
                "Audio capture flow and folder setup need review.",
                "The next transcription decision should be prepared before Friday."
            ],
            actionItems: actions,
            providerName: providerName
        )
    }

    private func suggestedTitle(from transcript: String) -> String? {
        let meaningfulWords = transcript
            .split { !$0.isLetter && !$0.isNumber }
            .map(String.init)
            .filter { $0.count > 2 }

        guard meaningfulWords.count >= 4 else { return nil }
        return "Launch Checklist Field Memo"
    }
}

public struct MockExportProvider: ExportProviding {
    public init() {}

    public func render(output: GeneratedOutput, format: ExportFormat) async throws -> Data {
        Data(output.content.utf8)
    }
}

public struct MockSubscriptionProvider: SubscriptionProviding {
    public var entitlement: String?

    public init(entitlement: String? = "preview") {
        self.entitlement = entitlement
    }

    public func currentEntitlement() async throws -> String? {
        entitlement
    }
}

public struct MockAuthenticationProvider: AuthenticationProviding {
    public var userID: UUID?

    public init(userID: UUID? = UUID()) {
        self.userID = userID
    }

    public func currentUserID() async throws -> UUID? {
        userID
    }
}

public actor MockAnalyticsProvider: AnalyticsProviding {
    public private(set) var events: [AnalyticsEvent] = []

    public init() {}

    public func track(_ event: AnalyticsEvent) async {
        events.append(event)
    }
}

public struct MockNotificationProvider: NotificationProviding {
    public init() {}

    public func requestAuthorization() async throws -> Bool {
        true
    }

    public func scheduleProcessingComplete(sessionID: UUID, title: String) async throws {}
}

public final class MockQuickSendProvider: QuickSendProviding {
    public private(set) var copiedText: String?
    public var shouldOpenInstagram: Bool

    public init(shouldOpenInstagram: Bool = false) {
        self.shouldOpenInstagram = shouldOpenInstagram
    }

    public func copy(_ text: String) async {
        copiedText = text
#if canImport(UIKit)
        UIPasteboard.general.string = text
#endif
    }

    public func copyAndOpenInstagram(_ text: String) async -> QuickSendResult {
        await copy(text)

#if canImport(UIKit)
        if shouldOpenInstagram, let url = URL(string: "instagram://app"), UIApplication.shared.canOpenURL(url) {
            let opened = await withCheckedContinuation { continuation in
                UIApplication.shared.open(url, options: [:]) { success in
                    continuation.resume(returning: success)
                }
            }
            return QuickSendResult(didCopy: true, didOpenTargetApp: opened, shouldPresentShareSheet: !opened)
        }
#endif

        return QuickSendResult(didCopy: true, didOpenTargetApp: false, shouldPresentShareSheet: true)
    }
}
